services:
  vpn-server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: vpn-server
    privileged: true
    ports:
      - "500:500/udp"
      - "4500:4500/udp"
    cap_add:
      - NET_ADMIN
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.accept_redirects=0
      - net.ipv4.conf.all.send_redirects=0
      - net.ipv4.ip_no_pmtu_disc=1
    networks:
      vpn-network:
        ipv4_address: 172.20.0.2
    restart: unless-stopped

networks:
  vpn-network:
    name: vpn-network
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/24
